// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// internalEmployeesDao is internal type for wrapping internal DAO implements.
type internalEmployeesDao = *internal.EmployeesDao

// employeesDao is the data access object for table employees.
// You can define custom methods on it to extend its functionality as you wish.
type employeesDao struct {
	internalEmployeesDao
}

var (
	// Employees is globally public accessible object for table employees operations.
	Employees = employeesDao{
		internal.NewEmployeesDao(),
	}
)

// Fill with you ideas below.
